[build]
  publish = "."

# CORS代理重定向规则
[[redirects]]
  from = "/api/*"
  to = "https://api.moonshot.cn/:splat"
  status = 200
  force = true

# SPA路由处理
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"